insert into books (id,title,author,price) values (1,'titulo1','autor1',1)
insert into books (id,title,author,price) values (2,'titulo2','autor2',2)
insert into books (id,title,author,price) values (3,'titulo3','autor3',3)
insert into books (id,title,author,price) values (4,'titulo4','autor4',4)
insert into books (id,title,author,price) values (5,'titulo5','autor5',5)